theme: jekyll-theme-slate
description: > # this means to ignore newlines until "baseurl:"
Welcome to my website! 
This website contains my projects that I did and my personal blogs and experience developing software application.
Thanks for visting my website!
